{% set name = "pick" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pick-{{ version }}.tar.gz
  sha256: f24434a845ae9265ebf7657fc224b9a203ac75aa576b568e061484a72e27be82

build:
  skip: true  # [py<36 or win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - poetry
  run:
    - dataclasses >=0.8,<0.9  # [py>=36 and py<37]
    - python
    # this would unblock the windows package
    # - windows-curses >=2.2.0,<3.0.0  # [win]

test:
  imports:
    - pick
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wong2/pick
  summary: Pick an option in the terminal with a simple GUI
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wong2
